# Generated by Django 3.2 on 2021-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresource',
            name='roomPartialCode',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
