# Generated by Django 3.2 on 2021-08-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210812_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bloger',
            new_name='blogger',
        ),
    ]
