# Generated by Django 3.2 on 2021-08-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210806_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='course',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teaches',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='ManuFactorar',
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
